version: '1'
services:
  web:
    container_name: ACADEMY-WEB
    hostname: academy-web
    ports:
      - "3000:3000"		
    image: academy-web
    environment:
      - API_URL=$API_URL
    depends_on:
      - api
  api:
    container_name: ACADEMY-API
    hostname: academy-api
    ports:
      - "8080:8080"
    image: academy-api
    environment:
      - DB_HOST=$DB_HOST
      - DB_PASSWORD=$DB_PASSWORD
      - DB_USERNAME=$DB_USERNAME
      - DB_NAME=$DB_NAME
# Below code is required to use a local containerised db
#    depends_on:
#      - db
#  db:
#    image: mysql
#    container_name: MYSQLDB
#    hostname: mysqldb
#    ports:
#      - "3306:3306"
#    command: --default-authentication-plugin=mysql_native_password
#    environment:
#      MYSQL_ROOT_PASSWORD: $DB_PASSWORD
